services:
  postgres:
    image: postgres:17
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: quests_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  quest-tracker-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: quest-tracker-api
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      STAGE: Local
      SERVER_PORT: 3000
      SERVER_BODY_LIMIT: 10
      SERVER_TIMEOUT: 30
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/quests_tracker_db
      JWT_ADVENTURER_SECRET: your-secret
      JWT_ADVENTURER_REFRESH_SECRET: your-refresh-secret
      JWT_GUILD_COMMANDER_SECRET: your-secret
      JWT_GUILD_COMMANDER_REFRESH_SECRET: your-refresh-secret

volumes:
  pgdata:
