apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:123456@postgres:5432/quests_tracker_db
  JWT_ADVENTURER_SECRET: your-secret
  JWT_ADVENTURER_REFRESH_SECRET: your-refresh-secret
  JWT_GUILD_COMMANDER_SECRET: your-secret
  JWT_GUILD_COMMANDER_REFRESH_SECRET: your-refresh-secret